version: '3'
services:
  coachwebapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: 02-vul-coachwebapp-coachwebapp
    ports:
      - "8081:8080"  # Map host port 8081 to container port 8080
    restart: always
